/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.magenic.nathan;

import org.junit.Test;
import static org.junit.Assert.*;

public class MyFunctionHandlerTest {
    @Test public void testSomeLibraryMethod() {
        MyFunctionHandler functionHandler = new MyFunctionHandler();
        String actual = functionHandler.handleRequest(null, null);
        assertEquals("Hello, World!", actual);
    }
}
